### PR TITLE
Restore the patch for iojs 2.5.0

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by aredridel** [comment]
This should fix things discussed in #21

**Comment by aredridel** [comment]
But! The patch needs to be updated -- this fails as written.

**Comment by hmalphettes** [comment]
The patch applies correctly now and `brew test aredridel/iojs/iojs` passed on my machine.

I figured we might as well merge this right now as master is broken for sure otherwise.

**Comment by bcomnes** [comment]
nice work everyone!

**Pull request merged**
