### PR TITLE
iojs-1.4.3 and npm-2.6.1

### PR DESCRIPTION
**Pull request by hmalphettes**

### CODE REVIEW

**Comment by bcomnes** [comment]
@hmalphettes Cool testing now!

**Comment by bcomnes** [comment]
Sweet looks great.  :+1:

**Comment by hmalphettes** [comment]
Now let's move the rest of my team to iojs thanks to your tap.
Thanks a lot!

**Comment by bcomnes** [comment]
Futzing with travis to speed the merge process up.

**Pull request merged**
